// src/app/header/Search.vue
<template>
    <div id="search">
        <div class="container">
            <input type="text" placeholder="Rechercher un arôme, ingrédient ..." />
            <img src="./images/search.svg" alt="" />
        </div>
    </div>
</template>

<script>
    export default {
        name: 'search'
    }
</script>

// src/app/header/SearchComponent.jsx
import React, { Component } from 'react';

class SearchComponent extends Component {

    render() {
        return (
            <div id="search" className="container">
                <div class="row">
                    <input type="text" placeholder="Rechercher un arôme, ingrédient ..." />
                    <img src="./images/search.svg" alt="" />
                </div>
            </div>
        );
    }

}

export default SearchComponent;
